In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing

In [19]:
df = pd.read_csv('data/trees.csv')
df

    Girth  Height  Volume
0     8.3      70    10.3
1     8.6      65    10.3
2     8.8      63    10.2
3    10.5      72    16.4
4    10.7      81    18.8
5    10.8      83    19.7
6    11.0      66    15.6
7    11.0      75    18.2
8    11.1      80    22.6
9    11.2      75    19.9
10   11.3      79    24.2
11   11.4      76    21.0
12   11.4      76    21.4
13   11.7      69    21.3
14   12.0      75    19.1
15   12.9      74    22.2
16   12.9      85    33.8
17   13.3      86    27.4
18   13.7      71    25.7
19   13.8      64    24.9
20   14.0      78    34.5
21   14.2      80    31.7
22   14.5      74    36.3
23   16.0      72    38.3
24   16.3      77    42.6
25   17.3      81    55.4
26   17.5      82    55.7
27   17.9      80    58.3
28   18.0      80    51.5
29   18.0      80    51.0
30   20.6      87    77.0

In [23]:
df['정도'] = np.where(df['Volume']>=40, '크다', '보통')
df.loc[df['Volume']<30, '정도'] = '적음'
print(df)

    Girth  Height  Volume  정도
0     8.3      70    10.3  적음
1     8.6      65    10.3  적음
2     8.8      63    10.2  적음
3    10.5      72    16.4  적음
4    10.7      81    18.8  적음
5    10.8      83    19.7  적음
6    11.0      66    15.6  적음
7    11.0      75    18.2  적음
8    11.1      80    22.6  적음
9    11.2      75    19.9  적음
10   11.3      79    24.2  적음
11   11.4      76    21.0  적음
12   11.4      76    21.4  적음
13   11.7      69    21.3  적음
14   12.0      75    19.1  적음
15   12.9      74    22.2  적음
16   12.9      85    33.8  보통
17   13.3      86    27.4  적음
18   13.7      71    25.7  적음
19   13.8      64    24.9  적음
20   14.0      78    34.5  보통
21   14.2      80    31.7  보통
22   14.5      74    36.3  보통
23   16.0      72    38.3  보통
24   16.3      77    42.6  크다
25   17.3      81    55.4  크다
26   17.5      82    55.7  크다
27   17.9      80    58.3  크다
28   18.0      80    51.5  크다
29   18.0      80    51.0  크다
30   20.6      87    77.0  크다